;; Este arquivo de "manifesto" pode ser passado para "guix package -m"
;; para reproduzir o conteúdo do seu perfil.  Isso é "simbólico": ele especifica
;; apenas nomes de pacotes.  Para reproduzir exatamente o mesmo perfil,
;; você também precisa capturar os canais sendo usados, conforme
;; retornado por "guix describe".  Veja a seção "Replicating Guix" no manual.

(specifications->manifest
  (list "emacs-doom-modeline"
        "emacs-consult-org-roam"
        "emacs-citar-org-roam"
        "emacs-org-roam"
        "emacs-org-roam-ui"
        "emacs-buffer-env"
        "emacs-tempel-collection"
        "emacs-tempel"
        "emacs-org-modern"
        "emacs-org-super-agenda"
        "emacs-magit"
        "emacs-jinx"
        "emacs-citar"
        "emacs-auctex"
        "tree-sitter-javascript"
        "tree-sitter-typescript"
        "emacs-pdf-tools"
        "emacs"
        "emacs-ledger-mode"
        "tree-sitter-go"
        "tree-sitter-html"
        "tree-sitter-css"
        "tree-sitter-rust"
        "tree-sitter-org"
        "tree-sitter-julia"
        "tree-sitter-latex"
        "tree-sitter-bibtex"
        "tree-sitter-bash"
        "tree-sitter-scheme"
        "tree-sitter-python"
        "python-tree-sitter"
        "ripgrep"
        "emacs-deadgrep"
        "emacs-yaml-mode"
        "emacs-embark"
        "emacs-eat"
        "emacs-geiser-guile"
        "emacs-consult-flycheck"
        "emacs-vertico"
        "emacs-cape"
        "emacs-consult"
        "emacs-corfu"
        "emacs-marginalia"
        "emacs-ef-themes"
        "emacs-treemacs"
        "emacs-jedi"
        "emacs-jupyter"
        "emacs-hyperbole"
        "emacs-go-mode"
        "emacs-typescript-mode"
        "emacs-orderless"
        "emacs-modus-themes"
        "emacs-crux"
        "emacs-meow"
        "emacs-flycheck"
        "emacs-dashboard"
        "emacs-request"
        "emacs-ox-gfm"
        "emacs-dirvish"
        "emacs-meson-mode"
        "emacs-markdown-mode"
        "emacs-all-the-icons-dired"
        "emacs-cmake-mode"
        "emacs-rainbow-delimiters"
        "emacs-use-package"
        "emacs-paredit"))
