;; Este arquivo de "manifesto" pode ser passado para "guix package -m"
;; para reproduzir o conteúdo do seu perfil.  Isso é "simbólico": ele especifica
;; apenas nomes de pacotes.  Para reproduzir exatamente o mesmo perfil,
;; você também precisa capturar os canais sendo usados, conforme
;; retornado por "guix describe".  Veja a seção "Replicating Guix" no manual.

(specifications->manifest
  (list "ripgrep"
        "emacs-ef-themes"
        "emacs-modus-themes"
        "emacs-consult-flycheck"
        "emacs-jinx"
        "emacs-org-modern"
        "emacs-consult-org-roam"
        "emacs-pdf-tools"
        "emacs-citar-org-roam"
        "emacs-citar"
        "emacs-hyperbole"
        "emacs-org-roam"
        "emacs-pgtk"
        "emacs-auctex"
        "emacs"
        "emacs-embark"
        "emacs-vertico"
        "emacs-corfu"
        "emacs-cape"
        "emacs-consult"
        "emacs-crux"
        "emacs-magit"
        "emacs-marginalia"
        "emacs-projectile"
        "emacs-deadgrep"
        "emacs-org-roam-ui"
        "emacs-meow"
        "emacs-flycheck"
        "emacs-dashboard"
        "emacs-request"
        "emacs-ox-gfm"
        "emacs-yasnippet"
        "emacs-dirvish"
        "emacs-meson-mode"
        "emacs-geiser-guile"
        "emacs-markdown-mode"
        "emacs-all-the-icons-dired"
        "emacs-cmake-mode"
        "emacs-orderless"
        "emacs-rainbow-delimiters"
        "emacs-use-package"
        "emacs-paredit"))
